services:
  web:
    image: ghcr.io/civanerbay/parpali-website:latest
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.parpali-website.rule=Host(`parpali-hennef.de`)
      - traefik.http.routers.parpali-website.tls=true
      - traefik.http.routers.parpali-website.entrypoints=web,websecure
      - traefik.http.routers.parpali-website.tls.certresolver=mytlschallenge
      - traefik.http.services.parpali-website.loadbalancer.server.port=3000
    env_file: .env
    volumes:
      - media_uploads:/app/media

networks:
  traefik:
    external: true
    name: root_default

volumes:
  media_uploads:
